#!/usr/bin/env python3
"""
check_all.py -- drive convert_cert.py over every certificate named in the task:
  - certs/P1_equiv_C6.json                       (our result)
  - certs/carreras/*.json                        (calibration of their tool)

For each certificate:
  1. Expand its ledger (invert/mul/conj/cycle) to elementary moves only, and
     to the official ac-r2-v1 numeric ids (0..13).
  2. Look up whether the certificate's declared "initial" presentation is one
     of the 10,115 official ac-* challenges (up to swap/inversion/rotation).
     If so, also look up "target".
  3. If "initial" matches an official challenge: build the alignment prefix
     (official initial_relators -> certificate's exact "initial") with
     andrews-curtis/make_cert.py's orbit_bridge, prepend it, and replay the
     WHOLE id sequence through the SAIR repo's own verifier.core.apply_move
     starting from the OFFICIAL initial_relators.  Also write a real
     submission.txt line and invoke their actual CLI
     (`python3 -m verifier ... --submission ...`) against the official
     manifest, to show exactly what it says (expected: E_NOT_TARGET, since
     none of our targets is the fixed (x, y)).
  4. If not: replay the (unaligned) id sequence directly from the
     certificate's own "initial" through verifier.core.apply_move (still
     their exact move implementation) -- this is the fallback the task asks
     for when their tool has no "arbitrary target" mode.
  5. Check the final state (from THEIR apply_move) lies in verify.py's own
     swap/inversion/rotation orbit of the certificate's declared "target".

Prints a machine-readable-ish report to stdout; sair_check/RESULTS.md is the
curated write-up of these outputs.
"""
import json
import os
import subprocess
import sys

import convert_cert as CC

AC_PROJECT = CC.AC_PROJECT
SAIR_REPO = CC.SAIR_REPO
CERTS = [
    os.path.join(AC_PROJECT, "certs/P1_equiv_C6.json"),
    os.path.join(AC_PROJECT, "certs/carreras/cert_ms3_yinvx2yinv_equiv_ak3.json"),
    os.path.join(AC_PROJECT, "certs/carreras/cert_ms3_yx2y_equiv_ak3.json"),
    os.path.join(AC_PROJECT, "certs/carreras/bottleneck_ak_f3_cert.json"),
    os.path.join(AC_PROJECT, "certs/carreras/cert_idx0_equiv_mirror.json"),
    os.path.join(AC_PROJECT, "certs/carreras/cert_sym_equiv_orphan1.json"),
]

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "generated")
os.makedirs(OUT_DIR, exist_ok=True)


def run_cli(challenge_id, ids, manifest_path):
    """Write a one-line submission.txt and invoke the *actual* SAIR CLI
    verifier, exactly as documented in competition/tools/verifier/README.md.
    Returns (returncode, stdout, submission_path)."""
    sub_path = os.path.join(OUT_DIR, "submission_%s.txt" % challenge_id)
    with open(sub_path, "w") as f:
        f.write("# generated by sair_check/check_all.py -- converted AC certificate\n")
        f.write("%s: %s\n" % (challenge_id, json.dumps(ids)))
    cmd = [
        sys.executable, "-m", "verifier",
        "--manifest", manifest_path,
        "--submission", sub_path,
        "--pretty",
    ]
    proc = subprocess.run(
        cmd, cwd=os.path.join(SAIR_REPO),
        env={**os.environ, "PYTHONPATH": os.path.join(SAIR_REPO, "competition", "tools")},
        capture_output=True, text=True,
    )
    return proc.returncode, proc.stdout, proc.stderr, sub_path, cmd


def process(cert_path, by_canon, by_id, manifest_path):
    name = os.path.relpath(cert_path, AC_PROJECT)
    cert = json.load(open(cert_path))
    initial = cert["initial"]
    target = cert["target"]
    claim = cert.get("claim", "AC_equivalence")
    assert claim == "AC_equivalence"

    # our own re-check, independent of anything below
    ok, msg, stats = CC.V.verify(cert)
    assert ok, "our own verify.py rejects %s: %s" % (name, msg)

    elem_moves, our_final = CC.flatten_to_elementary(cert["moves"], initial)
    main_ids = [CC.to_official_id(mv) for mv in elem_moves]

    report = {
        "cert": name,
        "n_cert_moves": len(cert["moves"]),
        "n_elementary_moves": len(elem_moves),
        "n_official_ids_main": len(main_ids),
        "our_verify_py": msg,
        "our_stats": stats,
    }

    hit = CC.find_official_challenge(by_canon, by_id, initial)
    if hit is None:
        report["official_challenge"] = None
        # fallback: replay directly from the certificate's own declared
        # "initial" through THEIR OWN apply_move (still their exact move
        # semantics; just not tied to a submitted official challenge id).
        final = CC.replay_official(initial, main_ids)
        report["prefix_ids"] = []
        report["official_replay_final"] = final
        report["matches_our_final"] = (final == our_final)
        report["endpoint_in_target_orbit"] = CC.in_target_orbit(final, target)
        report["cli"] = None
        return report

    challenge_id, official_initial = hit
    report["official_challenge"] = challenge_id
    report["official_initial_relators"] = official_initial

    prefix_moves, aligned = CC.alignment_moves(official_initial, initial)
    prefix_ids = [CC.to_official_id(mv) for mv in prefix_moves]
    full_ids = prefix_ids + main_ids

    final = CC.replay_official(official_initial, full_ids)
    report["prefix_ids"] = prefix_ids
    report["n_prefix_ids"] = len(prefix_ids)
    report["n_official_ids_total"] = len(full_ids)
    report["official_replay_final"] = final
    report["matches_our_final"] = (final == our_final)
    report["endpoint_in_target_orbit"] = CC.in_target_orbit(final, target)

    # also check the target itself, if it happens to be an official challenge
    thit = CC.find_official_challenge(by_canon, by_id, target)
    report["target_official_challenge"] = thit[0] if thit else None

    rc, out, err, sub_path, cmd = run_cli(challenge_id, full_ids, manifest_path)
    report["cli"] = {
        "command": " ".join(cmd) + "  (cwd=%s, PYTHONPATH=competition/tools)" % SAIR_REPO,
        "submission_file": sub_path,
        "returncode": rc,
        "stdout": out,
        "stderr": err,
    }
    return report


def main():
    manifest = CC.load_manifest()
    manifest_path = os.path.join(
        SAIR_REPO, "competition/tools/verifier/data/manifest.json")
    by_id, by_canon = CC.build_ac_index(manifest)

    reports = []
    for cert_path in CERTS:
        print("=== %s ===" % os.path.relpath(cert_path, AC_PROJECT), file=sys.stderr)
        r = process(cert_path, by_canon, by_id, manifest_path)
        reports.append(r)
        print(json.dumps({k: v for k, v in r.items() if k not in ("cli",)},
                          indent=2)[:2000], file=sys.stderr)

    out_path = os.path.join(OUT_DIR, "report.json")
    with open(out_path, "w") as f:
        json.dump(reports, f, indent=2)
    print("wrote", out_path, file=sys.stderr)


if __name__ == "__main__":
    main()
